# Header Menu
menu:
  Home:
    icon: fa-home
    url: /
  Blog:
    icon: fa-newspaper-o
    url: /articles/ # can set archive-dir in root config to custom value

rss: /atom.xml

# Content
excerpt_link: 続きを読む

# Featured Post Display Count
featured_count: 10

# 一覧画面のタグ表示
tag_display_min_count: 15

# Integrations(GA4 プロパティ)
google_analytics: G-X1C28R8H0M

# Social
social:
  github: https://github.com/future-architect
  twitter: https://twitter.com/future_techblog
  rss: atom.xml

# Miscellaneous
color_scheme: custom   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "twsrc%5Etfw" # as a string, from https://publish.twitter.com/?buttonType=MentionButton&dnt=1&lang=ja&query=https%3A%2F%2Ftwitter.com%2Ffuture_techblog&widget=Timeline
twitter_username: future_techblog # twitter username without the @

about: 経営とITをデザインする、フューチャーの技術ブログです。業務で利用している幅広い技術について紹介します。<br /><br /><a href="http://www.future.co.jp/">http://www.future.co.jp/</a>
email: techblog@future.co.jp
